### ISSUE TITLE
Add support for retrieving a public URL

### ISSUE THREAD

**Issue by bryan-vh** [satishbabariya/storage-swift#10]
# Support retrieving a public URL for an asset in a public bucket

## Is your feature request related to a problem? Please describe.

In order to better mirror the JS implementation, there should be support for retrieving a public URL for an asset in a public bucket. See here: https://supabase.com/docs/reference/javascript/storage-from-getpublicurl

## Describe the solution you'd like

Would like to add a method to the StorageFileApi class that adds support for this.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by bryan-vh** [comment]
@grsouza just opened a PR for this #11. I didn't realize that a simple workaround while I wait for this PR to be merged is you can just do `\(bucketId)/\(path)` to get the public facing URL as mentioned here: https://github.com/supabase/storage-js/blob/main/src/packages/StorageFileApi.ts in the comments above the method. That being said, just a nice-to-have and keeps this lib consistent with the others.

**Comment by maail** [comment]
Closing this since the PR has been merged.
